# Generated by Django 4.2.1 on 2023-06-07 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenesOferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='img_ofertas/', verbose_name='Imagen Oferta')),
            ],
            options={
                'verbose_name': 'Imagen de Oferta',
                'verbose_name_plural': 'Imagenes de Ofertas',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('cantidad', models.PositiveSmallIntegerField(default=1, verbose_name='Cantidad')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Valor')),
                ('material', models.CharField(choices=[('PLÁSTICO', 'PLÁSTICO'), ('VIDRIO', 'VIDRIO'), ('PAPEL', 'PAPEL'), ('CARTÓN', 'CARTÓN'), ('METAL', 'METAL'), ('OTROS', 'OTROS')], max_length=20, verbose_name='Material')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo/Inactivo')),
                ('vendido', models.BooleanField(default=False, verbose_name='Vendido')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('imagenes', models.ManyToManyField(to='management.imagenesoferta', verbose_name='Imagenes de la Oferta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': ('Ofertas',),
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Venta')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.oferta', verbose_name='Oferta')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha_venta'],
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Comprador')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['-id'],
            },
        ),
    ]
