# Generated by Django 4.2.1 on 2023-06-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_notificacion_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='visto',
            field=models.BooleanField(default=False, verbose_name='Visto'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='visto',
            field=models.BooleanField(default=False, verbose_name='Visto'),
        ),
    ]
