# Generated by Django 4.2.1 on 2023-06-25 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_oferta_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='oferta',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='management.oferta', verbose_name='Oferta'),
        ),
    ]
