# Generated by Django 4.2.1 on 2023-06-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(max_length=255, verbose_name='Teléfono'),
        ),
    ]
